from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import FileResponse
from backend.app.database import get_collection
from backend.app.auth import get_current_user
import os
import tempfile
import pandas as pd
import numpy as np

router = APIRouter(prefix="/analytics", tags=["Analytics & Reports"])

@router.get("/campus-dashboard")
def get_campus_dashboard():
    """Returns analytics data for common illnesses, student health trends, appointments, and emergencies."""
    # Retrieve data from DB (or generate dummy metrics for seeding if collections are empty)
    symptoms_col = get_collection("symptoms")
    emergency_col = get_collection("emergency_cases")
    appt_col = get_collection("appointments")
    score_col = get_collection("health_scores")
    
    # 1. Common Illnesses
    illnesses = ["Seasonal Flu", "Acute Pharyngitis", "Asthma", "Allergy Flare", "Migraine", "Gastroenteritis"]
    counts = [symptoms_col.count_documents({"analysis.conditions": name}) for name in illnesses]
    if sum(counts) == 0:
        counts = [15, 8, 4, 12, 10, 6] # Seed dummy stats for charts if database empty
        
    illness_data = [{"name": name, "count": count} for name, count in zip(illnesses, counts)]
    
    # 2. Appointments by Month
    months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
    appt_counts = [appt_col.count_documents({"date": {"$regex": f"-0{i+1}-"}}) for i in range(len(months))]
    if sum(appt_counts) == 0:
        appt_counts = [35, 42, 50, 28, 48, 62] # Demo stats
    appt_data = [{"month": month, "count": count} for month, count in zip(months, appt_counts)]
    
    # 3. Emergency Cases
    total_emergencies = emergency_col.count_documents({})
    resolved_emergencies = emergency_col.count_documents({"resolved": True})
    active_emergencies = total_emergencies - resolved_emergencies
    
    if total_emergencies == 0:
        active_emergencies = 2
        resolved_emergencies = 18
        
    emergency_data = {
        "active": active_emergencies,
        "resolved": resolved_emergencies
    }
    
    # 4. Student Health Scores (Grouped by Category)
    categories = ["Low Risk", "Medium Risk", "High Risk", "Critical"]
    cat_counts = [
        score_col.count_documents({"risk_category": "Low"}),
        score_col.count_documents({"risk_category": "Medium"}),
        score_col.count_documents({"risk_category": "High"}),
        score_col.count_documents({"risk_category": "Critical"})
    ]
    if sum(cat_counts) == 0:
        cat_counts = [120, 45, 14, 3] # Demo stats
    score_data = [{"category": cat, "count": count} for cat, count in zip(categories, cat_counts)]
    
    return {
        "illnesses": illness_data,
        "appointments": appt_data,
        "emergencies": emergency_data,
        "health_scores": score_data
    }

@router.get("/report/pdf")
def generate_health_report(current_user: dict = Depends(get_current_user)):
    """Generates a comprehensive PDF health card for the current student."""
    # Find student profile
    student = get_collection("students").find_one({"email": current_user["email"]})
    if not student:
        raise HTTPException(status_code=404, detail="Student profile not found")
        
    # Get last 5 health score records
    score_col = get_collection("health_scores")
    scores = list(score_col.find({"student_email": current_user["email"]}).limit(5))
    
    # Get vaccine list
    vacc_col = get_collection("vaccinations")
    vaccines = list(vacc_col.find({"student_email": current_user["email"]}))
    
    # Write to a temporary file
    temp_dir = tempfile.gettempdir()
    pdf_path = os.path.join(temp_dir, f"health_report_{student.get('student_id', 'temp')}.pdf")
    
    try:
        from fpdf import FPDF
        
        class QuadMedicReport(FPDF):
            def header(self):
                # Design background header bar
                self.set_fill_color(22, 160, 133) # Teal color
                self.rect(0, 0, 210, 40, 'F')
                self.set_text_color(255, 255, 255)
                self.set_font("Arial", 'B', 20)
                self.cell(0, 10, "QUADMEDIC HEALTH REPORT CARD", 0, 1, 'C')
                self.set_font("Arial", 'I', 10)
                self.cell(0, 5, "AI-Powered Smart Healthcare Ecosystem for Educational Institutions", 0, 1, 'C')
                self.ln(15)
                
            def footer(self):
                self.set_y(-15)
                self.set_font("Arial", 'I', 8)
                self.set_text_color(128, 128, 128)
                self.cell(0, 10, f"Page {self.page_no()} | Generated by QuadMedic AI Engine", 0, 0, 'C')
                
        pdf = QuadMedicReport()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)
        
        # 1. Demographics
        pdf.set_fill_color(240, 248, 255) # light AliceBlue
        pdf.rect(10, 45, 190, 45, 'F')
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", 'B', 12)
        pdf.set_xy(15, 48)
        pdf.cell(0, 6, "STUDENT INFORMATION", 0, 1)
        pdf.set_font("Arial", '', 10)
        pdf.cell(90, 5, f"Name: {student.get('name', 'N/A')}", 0, 0)
        pdf.cell(90, 5, f"Student ID: {student.get('student_id', 'N/A')}", 0, 1)
        pdf.cell(90, 5, f"Department: {student.get('department', 'N/A')}", 0, 0)
        pdf.cell(90, 5, f"Year: {student.get('year', 'N/A')}", 0, 1)
        pdf.cell(90, 5, f"Blood Group: {student.get('blood_group', 'N/A')}", 0, 0)
        pdf.cell(90, 5, f"Allergies: {', '.join(student.get('allergies', [])) or 'None'}", 0, 1)
        pdf.cell(0, 5, f"Chronic Conditions: {', '.join(student.get('chronic_conditions', [])) or 'None'}", 0, 1)
        
        # 2. Health Scores History Table
        pdf.set_xy(10, 95)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 6, "RECENT AI HEALTH RISKS & METRICS LOGS", 0, 1)
        
        # Header Row
        pdf.set_fill_color(22, 160, 133)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Arial", 'B', 10)
        pdf.cell(40, 7, "Date/Time", 1, 0, 'C', True)
        pdf.cell(30, 7, "BMI", 1, 0, 'C', True)
        pdf.cell(40, 7, "Sleep/Water", 1, 0, 'C', True)
        pdf.cell(40, 7, "Health Score", 1, 0, 'C', True)
        pdf.cell(40, 7, "Risk Category", 1, 1, 'C', True)
        
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", '', 9)
        if not scores:
            pdf.cell(190, 8, "No health calculations logged yet.", 1, 1, 'C')
        else:
            for s in scores[:5]:
                # Format time
                timestamp = s.get("timestamp", "N/A")
                if not isinstance(timestamp, str) or "-" not in timestamp:
                    import datetime
                    timestamp = datetime.datetime.now().strftime("%Y-%m-%d")
                else:
                    timestamp = timestamp[:10]
                pdf.cell(40, 7, timestamp, 1, 0, 'C')
                pdf.cell(30, 7, f"{s.get('bmi', 'N/A')}", 1, 0, 'C')
                pdf.cell(40, 7, f"{s.get('sleep_hours', 0)}h / {s.get('water_intake_l', 0)}L", 1, 0, 'C')
                pdf.cell(40, 7, f"{s.get('health_score', 0)}/100", 1, 0, 'C')
                risk = s.get('risk_category', 'N/A')
                pdf.cell(40, 7, risk, 1, 1, 'C')
                
        # 3. Vaccination Tracker
        pdf.ln(8)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 6, "VACCINATION LOGS", 0, 1)
        
        # Header Row
        pdf.set_fill_color(22, 160, 133)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Arial", 'B', 10)
        pdf.cell(60, 7, "Vaccine Name", 1, 0, 'C', True)
        pdf.cell(40, 7, "Dose Number", 1, 0, 'C', True)
        pdf.cell(45, 7, "Date Administered", 1, 0, 'C', True)
        pdf.cell(45, 7, "Administered By", 1, 1, 'C', True)
        
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", '', 9)
        if not vaccines:
            pdf.cell(190, 8, "No vaccinations logged in system.", 1, 1, 'C')
        else:
            for v in vaccines:
                pdf.cell(60, 7, v.get("vaccine_name", "N/A"), 1, 0, 'C')
                pdf.cell(40, 7, f"Dose {v.get('dose_number', 1)}", 1, 0, 'C')
                pdf.cell(45, 7, v.get("date_administered", "N/A"), 1, 0, 'C')
                pdf.cell(45, 7, v.get("administered_by", "N/A"), 1, 1, 'C')
                
        # Save PDF file
        pdf.output(pdf_path)
        return FileResponse(pdf_path, media_type="application/pdf", filename=f"health_report_{student.get('student_id', 'temp')}.pdf")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"PDF generation failed: {e}")

@router.get("/risk-predictions")
def get_risk_predictions(current_user: dict = Depends(get_current_user)):
    """Returns the list of latest student health risk scores for predictive dashboard."""
    if current_user.get("role") not in ["doctor", "admin"]:
        raise HTTPException(status_code=403, detail="Medical staff or Admin privileges required")
        
    score_col = get_collection("health_scores")
    students_col = get_collection("students")
    
    try:
        pipeline = [
            {"$sort": {"timestamp": -1}},
            {
                "$group": {
                    "_id": "$student_email",
                    "latest_score": {"$first": "$$ROOT"}
                }
            }
        ]
        results = list(score_col.aggregate(pipeline))
    except Exception:
        results = []
        
    predictions = []
    
    for r in results:
        email = r["_id"]
        latest = r["latest_score"]
        
        student = students_col.find_one({"email": email})
        name = student.get("name", "Unknown Student") if student else "Unknown Student"
        
        predictions.append({
            "name": name,
            "email": email,
            "health_score": latest.get("health_score", 100),
            "risk_category": latest.get("risk_category", "Low"),
            "symptoms": latest.get("symptoms", "None"),
            "timestamp": latest.get("timestamp", "")
        })
        
    predictions.sort(key=lambda x: x["health_score"])
    
    if not predictions:
        predictions = [
            {
                "name": "Sarah Connor",
                "email": "sarah.c@quadmedic.edu",
                "health_score": 28.5,
                "risk_category": "Critical",
                "symptoms": "Severe chest pain, short of breath, asthma history",
                "timestamp": "2026-06-09 14:30:12"
            },
            {
                "name": "John Doe",
                "email": "john.doe@quadmedic.edu",
                "health_score": 42.0,
                "risk_category": "High",
                "symptoms": "Chronic fatigue, severe persistent headaches",
                "timestamp": "2026-06-09 15:45:22"
            },
            {
                "name": "David Miller",
                "email": "david.m@quadmedic.edu",
                "health_score": 55.0,
                "risk_category": "Medium",
                "symptoms": "Mild cough, slight breathing tightness",
                "timestamp": "2026-06-09 16:10:05"
            }
        ]
        
    return predictions
